version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - DATABASE_PATH=/app/data/questgo.json
      - CORS_ORIGIN=http://2.56.179.161,http://localhost:3000,http://questgo.ru,https://questgo.ru
    volumes:
      - backend_data:/app/data
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=http://2.56.179.161,http://localhost:3000,http://questgo.ru,https://questgo.ru
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "2.56.179.161:80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
